 
# Data Configuration
data:
  input_columns: &input_cols
    - volt1
    - volt2 
    - amp1
    - amp2
    - FQtyL
    - FQtyR
    - E1 FFlow
    - E1 OilT 
    - E1 OilP
    - E1 RPM
    - E1 CHT1
    - E1 CHT2
    - E1 CHT3
    - E1 CHT4
    - E1 EGT1
    - E1 EGT2
    - E1 EGT3
    - E1 EGT4
    - OAT
    - IAS
    - VSpd
    - NormAc
    - AltMSL
  batch_size: 32
  num_workers: 4
  nfold: 5

# Training Configuration  
training:
  epochs: 100
  learning_rate: 0.001
  weight_decay: 0.0001
  early_stopping_patience: 10
  model_loss_type: bce
  augment: True
  predict: False

# Model Configuration
model:
  input_size: 23  # Length of input_columns
  hidden_size: 64
  num_layers: 2
  dropout: 0.2

# Logging Configuration
logging:
  log_interval: 100
  save_model: True
  model_dir: "models/"
  tensorboard_dir: "runs/"