
# Base configuration shared across models
defaults: &defaults
  input_columns: &input_cols
    - volt1
    - volt2 
    - amp1
    - amp2
    - FQtyL
    - FQtyR
    - E1 FFlow
    - E1 OilT 
    - E1 OilP
    - E1 RPM
    - E1 CHT1
    - E1 CHT2
    - E1 CHT3
    - E1 CHT4
    - E1 EGT1
    - E1 EGT2
    - E1 EGT3
    - E1 EGT4
    - OAT
    - IAS
    - VSpd
    - NormAc
    - AltMSL
  batch_size: 32
  num_workers: 4
  nfold: 5

# Model Configurations
models:
  rocket:
    <<: *defaults
    architecture: "ROCKET"
    num_kernels: 10000
    kernel_length: 9
    padding: True
    
  ocsvm:
    <<: *defaults
    architecture: "OCSVM"
    kernel: "rbf"
    nu: 0.1
    gamma: "scale"
    
  isolation_forest:
    <<: *defaults
    architecture: "IsolationForest"
    n_estimators: 100
    contamination: "auto"
    max_samples: "auto"
    
  autoencoder:
    <<: *defaults
    architecture: "Autoencoder"
    encoder_layers: [128, 64, 32]
    decoder_layers: [32, 64, 128]
    latent_dim: 16
    dropout: 0.2

# Hyperparameter Search Spaces
hyperparameter_search:
  rocket:
    num_kernels: [5000, 10000, 15000]
    kernel_length: [7, 9, 11]
    
  ocsvm:
    kernel: ["rbf", "linear", "poly"]
    nu: [0.01, 0.05, 0.1]
    gamma: ["scale", "auto", 0.1, 0.01]
    
  isolation_forest:
    n_estimators: [50, 100, 200]
    contamination: [0.1, 0.2, "auto"]
    max_samples: [100, "auto"]
    
  autoencoder:
    encoder_layers: [[128, 64, 32], [64, 32, 16], [256, 128, 64]]
    latent_dim: [8, 16, 32]
    dropout: [0.1, 0.2, 0.3]
    learning_rate: [0.0001, 0.001, 0.01]



