model:
  name: "rocket_ocsvm"
  rocket:
    n_kernels: 10000
    kss: [7, 9, 11]
    channels_in: 23
    sequence_length: 4096
    
  ocsvm:
    kernel: "rbf"
    gamma: "scale"
    nu: 0.01

training:
  cv_folds: 5
  repetitions: 10
  
tuning:
  method: "optuna"
  n_trials: 100
  timeout: 72000
  params:
    rocket:
      n_kernels:
        type: "int"
        low: 1000
        high: 20000
        step: 1000
    ocsvm:
      kernel:
        type: "categorical"
        choices: ["rbf", "linear", "poly"]
      nu:
        type: "float"
        low: 0.01
        high: 0.5
