defaults:
  seed: 42
  device: "cuda"
  num_workers: 4

data:
  path: "data/NGAFID_MC_C37.csv"
  batch_size: 32
  sequence_length: 4096
  features: [
    'volt1', 'volt2', 'amp1', 'amp2', 'FQtyL', 'FQtyR', 'E1 FFlow',
    'E1 OilT', 'E1 OilP', 'E1 RPM', 'E1 CHT1', 'E1 CHT2', 'E1 CHT3',
    'E1 CHT4', 'E1 EGT1', 'E1 EGT2', 'E1 EGT3', 'E1 EGT4', 'OAT', 'IAS',
    'VSpd', 'NormAc', 'AltMSL'
  ]

logging:
  project_name: "anomaly_detection"
  experiment_name: "${now:%Y-%m-%d_%H-%M-%S}"
  log_dir: "logs"

wandb:
  enabled: true
  project: "anomaly_detection"
  entity: "your_username"
